# Generated by Django 5.0.3 on 2024-04-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_profile_image_onlineuser'),
        ('User', '0005_alter_user_managers'),
    ]

    operations = [
    ]
