# Generated by Django 5.0.3 on 2024-04-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='educations',
            field=models.ManyToManyField(to='User.education'),
        ),
    ]
