# Generated by Django 5.0.3 on 2024-04-04 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0001_initial'),
        ('Tag', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='tag_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tag.taglist'),
        ),
    ]
