# Generated by Django 5.0.3 on 2024-04-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0002_feed_tag_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_type',
            field=models.CharField(choices=[('post', 'Post'), ('idea', 'Idea')], default='post', max_length=10),
        ),
    ]
