# Generated by Django 5.0.3 on 2024-04-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0002_remove_feed_tag_list_feed_tags'),
        ('Tag', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagList',
        ),
    ]
