# Generated by Django 5.0.3 on 2024-04-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taglist',
            name='content_type',
        ),
    ]
