# Generated by Django 5.0.3 on 2024-04-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0003_taglist_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='taglist',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='Tag.tag'),
        ),
    ]
