# Generated by Django 5.0.3 on 2024-04-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0002_feed_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], max_length=10, null=True),
        ),
    ]
