# Generated by Django 5.0.3 on 2024-04-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0002_remove_feed_tag_list_feed_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
