# Generated by Django 5.0.3 on 2024-04-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0002_rename_postreport_feedreport'),
        ('Feed', '0004_collaborator_created_at_notification_collaborator_and_more'),
    ]

    operations = [
    ]
