# Generated by Django 5.0.3 on 2024-04-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0004_alter_feed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feed_images/'),
        ),
    ]
