# Generated by Django 5.0.3 on 2024-04-14 11:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0005_alter_feed_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='tags',
        ),
        migrations.AddField(
            model_name='feed',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
